<?php

/**
 * Core config
 **/

return array(
	'cache_time'      => '110820171043',
	'assets_uri'  		=> get_template_directory_uri() . '/assets/',
	'shortcodes_dir'  => get_template_directory() . '/core/shortcodes/',
	'shortcodes_uri'  => get_template_directory_uri() . '/core/shortcodes/',
	'widgets_dir'     => get_template_directory() . '/core/widgets/',
	'widgets_uri'     => get_template_directory_uri() . '/core/widgets/',
	'social_profiles' => array(
		'facebook_url'    => esc_html__( 'Facebook URL', 'trends' ),
		'twitter_url'     => esc_html__( 'Twitter URL', 'trends' ),
		'instagram_url'   => esc_html__( 'Instagram URL', 'trends' ),
		'google_plus_url' => esc_html__( 'Google Plus URL', 'trends' ),
		'pinterest_url'   => esc_html__( 'Pinterest URL', 'trends' ),
		'linkedin_url'    => esc_html__( 'LinkedIn URL', 'trends' ),
		'youtube_url'     => esc_html__( 'YouTube URL', 'trends' ),
		'vimeo_url'       => esc_html__( 'Vimeo URL', 'trends' ),
		'dribbble_url'    => esc_html__( 'Dribbble URL', 'trends' ),
		'behance_url'     => esc_html__( 'Behance URL', 'trends' ),
		'tumblr_url'      => esc_html__( 'Tumblr URL', 'trends' ),
		'flickr_url'      => esc_html__( 'Flickr URL', 'trends' ),
		'medium_url'      => esc_html__( 'Medium URL', 'trends' ),
	),
	'social_icons'    => array(
		'facebook_url'    => 'fa fa-facebook',
		'twitter_url'     => 'fa fa-twitter',
		'instagram_url'   => 'fa fa-instagram',
		'google_plus_url' => 'fa fa-google-plus',
		'pinterest_url'   => 'fa fa-pinterest-p',
		'linkedin_url'    => 'fa fa-linkedin',
		'youtube_url'     => 'fa fa-youtube-play',
		'vimeo_url'       => 'fa fa-vimeo',
		'dribbble_url'    => 'fa fa-dribbble',
		'behance_url'     => 'fa fa-behance',
		'tumblr_url'      => 'fa fa-tumblr',
		'flickr_url'      => 'fa fa-flickr',
		'medium_url'      => 'fa fa-medium',
	),
	'animations'      => array(
		'bounce'            => esc_html__( 'Bounce', 'trends' ),
		'pulse'             => esc_html__( 'Pulse', 'trends' ),
		'tada'              => esc_html__( 'Tada', 'trends' ),
		'wobble'            => esc_html__( 'Wobble', 'trends' ),
		'jello'             => esc_html__( 'Jello', 'trends' ),
		'bounceIn'          => esc_html__( 'Bounce In', 'trends' ),
		'bounceInDown'      => esc_html__( 'Bounce In Down', 'trends' ),
		'bounceInLeft'      => esc_html__( 'Bounce In Left', 'trends' ),
		'bounceInRight'     => esc_html__( 'Bounce In Right', 'trends' ),
		'bounceInUp'        => esc_html__( 'Bounce In Up', 'trends' ),
		'fadeIn'            => esc_html__( 'Fade In', 'trends' ),
		'fadeInDown'        => esc_html__( 'Fade In Down', 'trends' ),
		'fadeInDownBig'     => esc_html__( 'Fade In Down Big', 'trends' ),
		'fadeInLeft'        => esc_html__( 'Fade In Left', 'trends' ),
		'fadeInLeftBig'     => esc_html__( 'Fade In Left Big', 'trends' ),
		'fadeInRight'       => esc_html__( 'Fade In Right', 'trends' ),
		'fadeInRightBig'    => esc_html__( 'Fade In Right Big', 'trends' ),
		'fadeInUp'          => esc_html__( 'Fade In Up', 'trends' ),
		'fadeInUpBig'       => esc_html__( 'Fade In Up Big', 'trends' ),
		'flip'              => esc_html__( 'Flip', 'trends' ),
		'flipInX'           => esc_html__( 'Flip in X', 'trends' ),
		'flipInY'           => esc_html__( 'Flip in Y', 'trends' ),
		'flipOutX'          => esc_html__( 'Flip out X', 'trends' ),
		'flipOutY'          => esc_html__( 'Flip out Y', 'trends' ),
		'lightSpeedIn'      => esc_html__( 'Light Speed In', 'trends' ),
		'rotateIn'          => esc_html__( 'Rotate In', 'trends' ),
		'rotateInDownLeft'  => esc_html__( 'Rotate In Down Left', 'trends' ),
		'rotateInDownRight' => esc_html__( 'Rotate In Down Right', 'trends' ),
		'rotateInUpLeft'    => esc_html__( 'Rotate In Up Left', 'trends' ),
		'rotateInUpRight'   => esc_html__( 'Rotate In Up Right', 'trends' ),
		'slideInUp'         => esc_html__( 'Slide In Up', 'trends' ),
		'slideInDown'       => esc_html__( 'Slide In Down', 'trends' ),
		'slideInLeft'       => esc_html__( 'Slide In Left', 'trends' ),
		'slideInRight'      => esc_html__( 'Slide In Right', 'trends' ),
		'zoomIn'            => esc_html__( 'Zoom In', 'trends' ),
		'zoomInDown'        => esc_html__( 'Zoom In Down', 'trends' ),
		'zoomInLeft'        => esc_html__( 'Zoom In Left', 'trends' ),
		'zoomInRight'       => esc_html__( 'Zoom In Right', 'trends' ),
		'zoomInUp'          => esc_html__( 'Zoom In Up', 'trends' ),
	),
);